ProTone/ProTone/ProTone/urls.py
from django.contrib import admin
from django.urls import path, include
from app_one import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('app_one/', include('app_one.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special', views.special, name='special'),
]

ProTone/ProTone/app_one/urls.py
from django.urls import path
from app_one import views

app_name = 'app_one'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('signup/', views.register, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('team/', views.team, name='team'),
    path('test/', views.test, name='test'),
]

ProTone/ProTone/app_one/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    portfolio_site = models.URLField(blank=True)
    
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

ProTone/ProTone/app_one/forms.py
from django import forms
from django.contrib.auth.models import User
from app_one.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

ProTone/ProTone/app_one/views.py
from django.shortcuts import render
from app_one.forms import UserForm, UserProfileInfoForm
#imprtong dajngo stuff
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def home(request):
    return render(request, 'app_one/home.html')

def team(request):
    return render(request, 'app_one/team.html')

def test(request):
    return render(request, 'app_one/test.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def special(request):
    return HttpResponse("You are logged in, hahah wtf")

    
def register(request):

    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            
            profile.user = user
            
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
                
            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
            
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        
    return render(request, 'app_one/signup.html', {'user_form':user_form,
                                                    'profile_form':profile_form,
                                                    'registered':registered})


def user_login(request):
    
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
            
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
            
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password {}" .format(username, password))
            return HttpResponse("invalid login details supplied")

    else:
        return render(request, 'app_one/login.html', {})

ProTone/ProTone/templates/app_one/extend.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Pro-Tone</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		{% comment %} <link rel="stylesheet" href="{% static 'assets/css/stylecss.css' %}" /> {% endcomment %}
	</head>
	<body class="is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header">

					<!-- Logo -->
						<h1><a href="index.html" id="logo">Pro-Tone <em>Your way to the future</em></a></h1>

					<!-- Nav -->
						<nav id="nav">
							<ul>
								<li><a href="{% url 'app_one:home' %}">Home</a></li>
								<li>
									<a href="#">Dropdown</a>
									<ul>
										<li><a href="#">1</a></li>
										<li><a href="#">2</a></li>
										<li><a href="#">3</a></li>
										<li>
											<a href="#">Submenu</a>
											<ul>
												<li><a href="#">1</a></li>
												<li><a href="#">2</a></li>
												<li><a href="#">3</a></li>
												<li><a href="#">4</a></li>
												<li><a href="#">5</a></li>
											</ul>
										</li>
										<li><a href="#">اخير</a></li>
									</ul>
								</li>
								{% if user.is_authenticated %}
								<li><a href="{% url 'app_one:test' %}">Pro-Tone Analyze</a></li>
								{% else %}
								<li><a>Pro-Tone Analyze login required</a></li>
								{% endif %}
								<li><a href="{% url 'app_one:team' %}">About the team</a></li>
								{% if user.is_authenticated %}
								<li><a href="{% url 'app_one:logout' %}">Logout</a></li>
								{% else %}
								<li><a href="{% url 'app_one:login' %}">Login</a></li>
								<li><a href="{% url 'app_one:signup' %}">Signup</a></li>
								{% endif %}
								
							</ul>
						</nav>

				</div>

                {% block body_block %}
                <!-- this take it to toher html -->
                {% endblock %}







			<!-- Footer -->
				<div id="footer">
					<div class="container">
						<div class="row">
							<section class="col-3 col-6-narrower col-12-mobilep">
								<h3>روابط لبعض الأشياء</h3>
								<ul class="links">
									<li><a href="#">تعليم</a></li>
									<li><a href="#">عمل</a></li>
									<li><a href="#">مابين عمل وتعلمين</a></li>
									<li><a href="#">الخخخخ</a></li>
									<li><a href="#">الخخ 2.</a></li>
								</ul>
							</section>
							<section class="col-3 col-6-narrower col-12-mobilep">
								<h3>روابط</h3>
								<ul class="links">
									<li><a href="#">وزاره تربيه والتعليم</a></li>
									<li><a href="#">شركة</a></li>
									<li><a href="#">مصادر تعليميه</a></li>
									<li><a href="#">الهخخخ</a></li>
								</ul>
							</section>
							<section class="col-6 col-12-narrower">
								<h3>للتواصل</h3>
								<form>
									<div class="row gtr-50">
										<div class="col-6 col-12-mobilep">
											<input type="text" name="name" id="name" placeholder="الاسم" />
										</div>
										<div class="col-6 col-12-mobilep">
											<input type="email" name="email" id="email" placeholder="اميل" />
										</div>
										<div class="col-12">
											<textarea name="message" id="message" placeholder="الرساله" rows="5"></textarea>
										</div>
										<div class="col-12">
											<ul class="actions">
												<li><input type="submit" class="button alt" value="إرسال الرساله" /></li>
											</ul>
										</div>
									</div>
								</form>
							</section>
						</div>
					</div>

					<!-- Icons -->
						<ul class="icons">
							<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon brands fa-github"><span class="label">GitHub</span></a></li>
							<li><a href="#" class="icon brands fa-linkedin-in"><span class="label">LinkedIn</span></a></li>
							<li><a href="#" class="icon brands fa-google-plus-g"><span class="label">Google+</span></a></li>
						</ul>

					<!-- Copyright -->
						<div class="copyright">
							<ul class="menu">
								<li>&copy; All rights reserved</li><li>Design: Basher</a></li>
							</ul>
						</div>

				</div>

		</div>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.dropotron.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.countup.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/mainjs.js' %}"></script>
			{% comment %} <script src="{% static 'assets/js/mainjs.js' %}"></script> {% endcomment %}

	</body>
</html>

ProTone/ProTone/templates/app_one/home.html
<!DOCTYPE html>
{% extends 'app_one/extend.html' %}
{% load static %}

{% block body_block %}


			<!-- Banner -->
            <section id="banner">
                <header>
                        <iframe
                        src=""
                        name="targetframe"
                        allowTransparency="true"
                        scrolling="no"
                        frameborder="0"
                        >
                        </iframe>
                    <h2>Pro-Tone: <em>the next Edtech idea technology to boost the libyan education </em></h2>
                    <a href="#" class="button">Learn More</a>
                </header>
            </section>

        <!-- Highlights -->
            <section class="wrapper style1">
                <div class="container">
                    <div class="row gtr-200">
                        <section class="col-4 col-12-narrower">
                            <div class="box highlight">
                                <i class="icon solid major fa-paper-plane"></i>
                                <h3>هذا مهم</h3>
                                <p>القرايا مهمه ياعرب</p>
                            </div>
                        </section>
                        <section class="col-4 col-12-narrower">
                            <div class="box highlight">
                                <i class="icon solid major fa-pencil-alt"></i>
                                <h3>هذا ايضا مهم</h3>
                                <p>تطبيق لخذيته في القرايا</p>
                            </div>
                        </section>
                        <section class="col-4 col-12-narrower">
                            <div class="box highlight">
                                <i class="icon solid major fa-wrench"></i>
                                <h3>اهم حاجه</h3>
                                <p>فلوس  مهمات</p>
                            </div>
                        </section>
                    </div>
                </div>
            </section>

        <!-- Gigantic Heading -->
            <section class="wrapper style2">
                <div class="container">
                    <header class="major">
                        <h2>هاذي ضفتها توا تقدر تضيف فيها شي حاجه</h2>
                        <p>وهنا تقدر تضيف اضافه على اضافه لدرتها</p>
                    </header>
                </div>
            </section>

        <!-- Posts -->
            <section class="wrapper style1">
                <div class="container">
                    <div class="row">
                        <section class="col-6 col-12-narrower">
                            <div class="box post">
                                <a href="#" class="image left"><img src="{% static 'images/pic01.jpg' %}" alt="" /></a>
                                <div class="inner">
                                    <h3>أول حاجه</h3>
                                    <p>مافيش حاجه </p>
                                </div>
                            </div>
                        </section>
                        <section class="col-6 col-12-narrower">
                            <div class="box post">
                                <a href="#" class="image left"><img src="{% static 'images/pic02.jpg' %}" alt="" /></a>
                                <div class="inner">
                                    <h3>ثاني حاجه</h3>
                                    <p>برضو مافيش</p>
                                </div>
                            </div>
                        </section>
                    </div>
                    <div class="row">
                        <section class="col-6 col-12-narrower">
                            <div class="box post">
                                <a href="#" class="image left"><img src="{% static 'images/pic03.jpg' %}" alt="" /></a>
                                <div class="inner">
                                    <h3>ثالث حاجه</h3>
                                    <p>Dتتوقعش حاجه </p>
                                </div>
                            </div>
                        </section>
                        <section class="col-6 col-12-narrower">
                            <div class="box post">
                                <a href="#" class="image left"><img src="{% static 'images/pic04.jpg' %}" alt="" /></a>
                                <div class="inner">
                                    <h3>رابع والاخيره</h3>
                                    <p>مافيش ايضا</p>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </section>

        <!-- CTA -->
            <section id="cta" class="wrapper style3">
                <div class="container">
                    <header>
                        <h2>هل أنت جاهز لإكمال رحلتك ؟</h2>
                        <a href="#" class="button">أضغط هنا!</a>
                    </header>
                </div>
            </section>







{% endblock  %}

ProTone/ProTone/templates/app_one/login.html
{% extends "app_one/extend.html" %}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />

<div class="login_cer">
    <h1>Please login</h1>
    <form action="{% url 'app_one:login' %}" method="post">
        {% csrf_token %}
        <label for="username">username</label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password:</label>
        <input type="password" name="password" value="">
        <input type="submit" name="" value="Login">
    </form>
</div>


{% endblock %}

ProTone/ProTone/templates/app_one/signup.html
{% extends "app_one/extend.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

ProTone/ProTone/templates/app_one/team.html
{% extends "app_one/extend.html" %}
{% load static %}
{% block body_block %}


<h1>dis is dat team lol</h1>


{% endblock  %}

ProTone/ProTone/templates/app_one/test.html
{% extends "app_one/extend.html" %}
{% block body_block %}
{% load static %}
<link rel="stylesheet" href="{% static 'assets/css/quizcss.css' %}" />

<body onload="NextQuestion(0)">
    <main>
        <!-- creating a modal for when quiz ends -->
        <div class="modal-container" id="score-modal">

            <div class="modal-content-container">

                <h1>Congratulations, Quiz Completed.</h1>

                <div class="grade-details">
                    <p>Attempts : 10</p>
                    <p>Wrong Answers : <span id="wrong-answers"></span></p>
                    <p>Right Answers : <span id="right-answers"></span></p>
                    <p>Grade : <span id="grade-percentage"></span>%</p>
                    <p ><span id="remarks"></span></p>
                </div>

                <div class="modal-button-container">
                    <button onclick="closeScoreModal()">Continue</button>
                </div>

            </div>
        </div>
<!-- end of modal of quiz details-->

        <div class="game-quiz-container">

            <div class="game-details-container">
                <h1>Score : <span id="player-score"></span> / 10</h1>
                <h1> Question : <span id="question-number"></span> / 10</h1>
            </div>

            <div class="game-question-container">
                <h1 id="display-question"></h1>
            </div>

            <div class="game-options-container">

               <div class="modal-container" id="option-modal">

                    <div class="modal-content-container">
                         <h1>Please Pick An Option</h1>

                         <div class="modal-button-container">
                            <button onclick="closeOptionModal()">Continue</button>
                        </div>

                    </div>

               </div>

                <span>
                    <input type="radio" id="option-one" name="option" class="radio" value="optionA" />
                    <label for="option-one" class="option" id="option-one-label"></label>
                </span>


                <span>
                    <input type="radio" id="option-two" name="option" class="radio" value="optionB" />
                    <label for="option-two" class="option" id="option-two-label"></label>
                </span>


                <span>
                    <input type="radio" id="option-three" name="option" class="radio" value="optionC" />
                    <label for="option-three" class="option" id="option-three-label"></label>
                </span>


                <span>
                    <input type="radio" id="option-four" name="option" class="radio" value="optionD" />
                    <label for="option-four" class="option" id="option-four-label"></label>
                </span>


            </div>

            <div class="next-button-container">
                <button onclick="handleNextQuestion()">Next Question</button>
            </div>

        </div>
    </main>
    <script src="{% static 'assets/js/quizjs.js' %}"></script>
</body>

{% endblock %}